# GitHub Actions
# https://help.github.com/en/articles/configuring-a-workflow
# good list of examples at http://www.thedreaming.org/2019/09/10/github-ci/
name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # schedule:
  #   - cron: "0 */12 * * *"

jobs:
  CI:
    name: Cypress Run
    runs-on: ubuntu-latest
    # Cypress Docker image - https://github.com/cypress-io/cypress-docker-images
    container: cypress/browsers:latest
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      fail-fast: false
      matrix:
        # Run on the following browsers according to docker image
        browser: [chrome]

        # Runs 3 copies of the current job in parallel
        containers: [1, 2, 3, 4, 5, 6]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # because of "record" and "parallel" parameters
      # these containers will load balance all found tests among themselves
      - name: Npm Install
        run: npm install
      - name: Cypress Run
        run: npx cypress run --record --key 57e297dc-ea87-4943-9f5b-8be1d05972c6 --group CI --browser ${{ matrix.browser }} --parallel

      # Upload videos and screenshots as artifacts
      - name: Upload Image Artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload Video Artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
