# GitHub Actions
# https://help.github.com/en/articles/configuring-a-workflow
# good list of examples at http://www.thedreaming.org/2019/09/10/github-ci/
name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  CI:
    name: Cypress Run
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        # Run on the following browsers according to docker image
        browser: [chrome]
    # Cypress Docker image - https://github.com/cypress-io/cypress-docker-images
    container: cypress/browsers:node12.16.1-chrome80-ff73
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # because of "record" and "parallel" parameters
      # these containers will load balance all found tests among themselves
      - name: Install Npm
        run: npm install
      - name: Cypress Run
        run: npx cypress run --record --key 57e297dc-ea87-4943-9f5b-8be1d05972c6 --parallel --browser ${{ matrix.browser }}

      # Upload videos and screenshots as artifacts
      - name: Upload Image Artifacts
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Video Artifacts
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
