# GitHub Actions
# https://help.github.com/en/articles/configuring-a-workflow
# good list of examples at http://www.thedreaming.org/2019/09/10/github-ci/
name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  install:
    name: Install NPM and Cypress
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master

      # install a specific version of Node using
      # https://github.com/actions/setup-node
      - name: Use Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install & Build
      - run:
        npm ci
        npm run build --if-present

  Test:
    name: Cypress Test
    runs-on: ubuntu-16.04
    needs: install
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Cypress Tests Run
        run: |
          npm start &
          npx cypress run --record --parallel
      - name: Artifact Generate
      - uses: actions/upload-artifact@master
        if: failure()
        with:
          name: screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@master
        with:
          name: videos
          path: cypress/videos
